Co-Labor-Project/Co-Labor-BE

co-labor/src/main/java/pelican/co_labor/config/test/DataLoader.java, co-labor/src/main/java/pelican/co_labor/controller/EnterpriseController.java, co-labor/src/main/java/pelican/co_labor/domain/enterprise/Enterprise.java, co-labor/src/main/java/pelican/co_labor/service/EnterpriseService.java
- #20 
<br>
- 기업 등록, 수정, 조회와 관련된 기능 추가
=> feat : add enterprise controller and service

co-labor/src/main/java/pelican/co_labor/controller/JobController.java, co-labor/src/main/java/pelican/co_labor/service/JobService.java
- 기존 채용 정보 페이지 관련 API의 기능을 최적화하고, 코드의 가독성을 높이며, 새로운 엔티티와 로그인 관련 기능을 반영하기 위함입니다.
- 유저가 채용공고를 조회할 때마다 조회수가 증가하도록 기능을 추가합니다.
<br>
-  #31 
<br>
1. **JobController 클래스 수정**:
- 채용 공고 조회 시 `views` 필드를 증가시키는 로직 추가.
- 기존 CRUD API를 유지하면서 필요한 리팩토링 진행.
2. **Job 엔티티 클래스 수정**:
- `views` 필드 추가하여 채용 공고 조회 시 증가하도록 설정.
- 생성 및 수정 시간 필드를 유지하면서 필요한 리팩토링 진행.
3. **JobRepository 인터페이스 수정**:
- 필요한 쿼리 메서드 추가 및 수정.
4. **JobService 클래스 수정**:
- 채용 공고 조회 시 `views` 필드를 증가시키는 로직 추가.
- 기존 CRUD 메서드를 유지하면서 필요한 리팩토링 진행.
<br>
- 채용 공고 조회 시 `views` 필드 증가 로직이 올바르게 동작하는지 확인 부탁드립니다.
- 리팩토링된 코드가 기존 기능에 영향을 미치지 않는지 검토 했습니다
=> feat: 리팩토링 채용 정보 페이지 API 및 조회수 증가 기능 추가

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/controller/AuthController.java, co-labor/src/main/java/pelican/co_labor/service/AuthService.java
=> feat: Added features related to login sessions

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/config/webconfig/WebConfig.java, co-labor/src/main/java/pelican/co_labor/service/OpenAIChatService.java
=> refc: 채팅 관련 수정 (토큰, 프롬프트,세션인증, 프론트랑 연결 )

co-labor/src/main/java/pelican/co_labor/controller/ReviewController.java, co-labor/src/main/java/pelican/co_labor/dto/ReviewDTO.java, co-labor/src/main/java/pelican/co_labor/repository/review/ReviewRepository.java, co-labor/src/main/java/pelican/co_labor/service/ReviewService.java
=> feat: Implement CRUD operations for Review API

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/controller/EnterpriseController.java, co-labor/src/main/java/pelican/co_labor/service/AuthService.java
=> feat: Add endpoint to map enterprise to user by enterprise ID

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/config/test/EnterpriseUserDummyDataLoader.java, co-labor/src/main/java/pelican/co_labor/repository/enterprise_user/EnterpriseUserRepository.java, co-labor/src/main/java/pelican/co_labor/service/SupportCenterService.java
=> Feat/#44 지원센터 서버킬때 로드 수정

co-labor/src/main/java/pelican/co_labor/config/test/DataLoader.java
=> feat: add 채용공고 관련 더미 데이터 in DataLoader

co-labor/src/main/java/pelican/co_labor/config/test/DataLoader.java, co-labor/src/main/java/pelican/co_labor/config/test/EnterpriseDummyDataLoader.java, co-labor/src/main/java/pelican/co_labor/config/test/EnterpriseUserDummyDataLoader.java
=> feat : add Enterprise Data

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/config/test/DataLoader.java, co-labor/src/main/java/pelican/co_labor/controller/ChattingController.java, co-labor/src/main/java/pelican/co_labor/service/ChattingService.java, co-labor/src/test/java/pelican/co_labor/controller/MainControllerTest.java, co-labor/src/test/java/pelican/co_labor/controller/SearchControllerTest.java
=> refactor: 개선된 대화 기록 관리 및 GPT-3.5 응답 처리 로직 추가

co-labor/src/main/java/pelican/co_labor/config/test/DataLoader.java, co-labor/src/main/java/pelican/co_labor/controller/EnterpriseController.java, co-labor/src/main/java/pelican/co_labor/controller/JobController.java, co-labor/src/main/java/pelican/co_labor/domain/enterprise/EnterpriseEng.java, co-labor/src/main/java/pelican/co_labor/domain/enterprise_user/EnterpriseUser.java, co-labor/src/main/java/pelican/co_labor/domain/job/JobEng.java, co-labor/src/main/java/pelican/co_labor/repository/enterprise/EnterpriseEngRepository.java, co-labor/src/main/java/pelican/co_labor/repository/enterprise_user/EnterpriseUserRepository.java, co-labor/src/main/java/pelican/co_labor/repository/job/JobEngRepository.java, co-labor/src/main/java/pelican/co_labor/service/EnterpriseService.java, co-labor/src/main/java/pelican/co_labor/service/JobService.java
=> feat: Added English tables for job postings and enterprise information

co-labor/src/main/java/pelican/co_labor/domain/hospital/Hospital.java
=> refc : hospital DB

co-labor/src/main/java/pelican/co_labor/controller/HospitalController.java, co-labor/src/main/java/pelican/co_labor/domain/hospital/Hospital.java, co-labor/src/main/java/pelican/co_labor/repository/hospital/HospitalRepository.java, co-labor/src/main/java/pelican/co_labor/service/HospitalService.java
=> refc: hospital all

co-labor/src/main/java/pelican/co_labor/controller/AuthController.java, co-labor/src/main/java/pelican/co_labor/controller/ChattingController.java, co-labor/src/main/java/pelican/co_labor/controller/EnterpriseController.java, co-labor/src/main/java/pelican/co_labor/controller/HospitalController.java, co-labor/src/main/java/pelican/co_labor/controller/JobController.java, co-labor/src/main/java/pelican/co_labor/controller/MainController.java, co-labor/src/main/java/pelican/co_labor/controller/ReviewController.java, co-labor/src/main/java/pelican/co_labor/controller/SearchController.java, co-labor/src/main/java/pelican/co_labor/controller/SupportCenterController.java
=> feat: swagger 어노테이션

co-labor/src/main/java/pelican/co_labor/controller/AuthController.java, co-labor/src/main/java/pelican/co_labor/controller/HospitalController.java, co-labor/src/main/java/pelican/co_labor/controller/MainController.java, co-labor/src/main/java/pelican/co_labor/controller/SearchController.java, co-labor/src/main/java/pelican/co_labor/service/HospitalService.java
=> refc : controller

co-labor/src/main/java/pelican/co_labor/test/Test.java
=> feat: Update enterprise type for records with null or empty type

co-labor/src/main/java/pelican/co_labor/controller/HospitalController.java, co-labor/src/main/java/pelican/co_labor/service/NaverGeocodingService.java
=> refc: add hospital data Reverse Geocoding

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/service/OpenAIChatService.java
=> refc : chatbot fine tuning

co-labor/src/main/java/pelican/co_labor/controller/ChattingController.java, co-labor/src/main/java/pelican/co_labor/service/ChattingService.java
=> feat : new chat activity

co-labor/build.gradle, co-labor/src/main/java/pelican/co_labor/controller/ReviewController.java
=> refc : review api SESSION

co-labor/src/main/java/pelican/co_labor/controller/JobController.java, co-labor/src/main/java/pelican/co_labor/service/JobService.java
=> Fix: Improve job posting update logic and strengthen permission checks

co-labor/src/main/java/pelican/co_labor/controller/EnterpriseController.java
=> fix : Change error response for unregistered enterprise to 200 OK
